import { StyleSheet } from 'react-native';

import { APP_COLORS, fonts } from '@/theme';

const cardShadow = {
  shadowColor: APP_COLORS.navy,
  shadowOpacity: 0.06,
  shadowRadius: 16,
  shadowOffset: { width: 0, height: 4 },
  elevation: 4,
} as const;

export const documentDetailCardStyles = StyleSheet.create({
  statusCard: {
    backgroundColor: APP_COLORS.white,
    borderRadius: 24,
    padding: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 14,
    ...cardShadow,
  },
  accessCard: {
    backgroundColor: APP_COLORS.white,
    borderRadius: 24,
    padding: 20,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    ...cardShadow,
  },
  accessCopy: {
    flex: 1,
    gap: 4,
  },
  accessCount: {
    color: APP_COLORS.primary,
    fontFamily: fonts.regular,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '800',
    marginTop: 2,
  },
  partyNameList: {
    gap: 4,
    marginTop: 8,
  },
  partyRoleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  partyName: {
    flex: 1,
    color: APP_COLORS.navy,
    fontFamily: fonts.regular,
    fontSize: 13,
    lineHeight: 17,
    fontWeight: '700',
  },
  partyRolePill: {
    overflow: 'hidden',
    borderRadius: 999,
    backgroundColor: APP_COLORS.surfaceSoft,
    color: APP_COLORS.primary,
    fontFamily: fonts.regular,
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '800',
    paddingHorizontal: 8,
    paddingVertical: 3,
    maxWidth: 96,
  },
  partyNameMuted: {
    color: APP_COLORS.textMuted,
    fontFamily: fonts.regular,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
  },
  accessAction: {
    minWidth: 104,
  },
  statusCopy: {
    flex: 1,
    gap: 4,
  },
  statusTitle: {
    color: APP_COLORS.navy,
    fontFamily: fonts.regular,
    fontSize: 17,
    lineHeight: 21,
    fontWeight: '800',
  },
  statusBody: {
    color: APP_COLORS.textMuted,
    fontFamily: fonts.regular,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '600',
  },
  statusPill: {
    overflow: 'hidden',
    borderRadius: 999,
    backgroundColor: '#EAF8F0',
    color: '#0C6B3A',
    fontFamily: fonts.regular,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '800',
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  cardIconBubble: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: APP_COLORS.surfaceSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  versionCard: {
    backgroundColor: APP_COLORS.white,
    borderRadius: 24,
    padding: 20,
    gap: 18,
    ...cardShadow,
  },
  versionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 14,
  },
  versionHeaderCopy: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  versionTitle: {
    color: APP_COLORS.navy,
    fontFamily: fonts.regular,
    fontSize: 18,
    lineHeight: 22,
    fontWeight: '800',
  },
  headerAction: {
    borderRadius: 999,
    backgroundColor: APP_COLORS.surfaceSoft,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  headerActionPressed: {
    opacity: 0.75,
  },
  headerActionText: {
    color: APP_COLORS.primary,
    fontFamily: fonts.regular,
    fontSize: 12,
    lineHeight: 14,
    fontWeight: '800',
  },
  timeline: {
    gap: 0,
  },
  timelineRow: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 12,
    borderRadius: 16,
    paddingRight: 4,
  },
  timelineRowPressed: {
    backgroundColor: APP_COLORS.surfaceSoft,
  },
  timelineDateColumn: {
    width: 82,
    paddingTop: 1,
  },
  timelineDate: {
    color: APP_COLORS.textMuted,
    fontFamily: fonts.regular,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '800',
  },
  timelineDateCurrent: {
    color: APP_COLORS.primary,
  },
  timelineLineColumn: {
    alignItems: 'center',
    width: 18,
  },
  timelineDot: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: APP_COLORS.borderSoft,
    borderWidth: 3,
    borderColor: APP_COLORS.white,
  },
  timelineDotCurrent: {
    backgroundColor: APP_COLORS.primary,
  },
  timelineLine: {
    flex: 1,
    width: 2,
    minHeight: 52,
    backgroundColor: APP_COLORS.borderSoft,
  },
  timelineContent: {
    flex: 1,
    paddingBottom: 18,
    gap: 6,
  },
  timelineTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap',
  },
  timelineLabel: {
    color: APP_COLORS.navy,
    fontFamily: fonts.regular,
    fontSize: 15,
    lineHeight: 18,
    fontWeight: '800',
  },
  timelineLabelCurrent: {
    color: APP_COLORS.primary,
  },
  versionStatus: {
    overflow: 'hidden',
    borderRadius: 999,
    backgroundColor: '#EAF8F0',
    color: '#0C6B3A',
    fontFamily: fonts.regular,
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '800',
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  timelineDescription: {
    color: APP_COLORS.textMuted,
    fontFamily: fonts.regular,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '600',
  },
  emptyTimelineText: {
    color: APP_COLORS.textMuted,
    fontFamily: fonts.regular,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '600',
  },
  versionViewIcon: {
    alignSelf: 'center',
  },
  confidenceCard: {
    backgroundColor: APP_COLORS.white,
    borderRadius: 24,
    padding: 20,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    ...cardShadow,
  },
  confidencePill: {
    overflow: 'hidden',
    borderRadius: 999,
    backgroundColor: APP_COLORS.surfaceSoft,
    color: APP_COLORS.primary,
    fontFamily: fonts.regular,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '800',
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
});
