import { StyleSheet } from 'react-native';

import { APP_COLORS, fonts } from '@/theme';

export const uploadDropzoneColors = {
  primary: APP_COLORS.primary,
  navy: APP_COLORS.navy,
  textMuted: APP_COLORS.textMuted,
  borderSoft: APP_COLORS.borderSoft,
  surface: APP_COLORS.white,
  surfaceSecondary: '#F7FBFF',
  surfaceSoft: APP_COLORS.surfaceSoft,
};

export const uploadDropzoneStyles = StyleSheet.create({
  card: {
    backgroundColor: uploadDropzoneColors.surface,
    borderRadius: 28,
    padding: 18,
    gap: 14,
    shadowColor: APP_COLORS.navy,
    shadowOpacity: 0.06,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 4 },
    elevation: 4,
  },
  top: {
    backgroundColor: uploadDropzoneColors.surfaceSecondary,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: uploadDropzoneColors.borderSoft,
    padding: 18,
    alignItems: 'center',
    gap: 10,
  },
  iconWrap: {
    width: 56,
    height: 56,
    borderRadius: 999,
    backgroundColor: uploadDropzoneColors.surfaceSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconWrapScanned: {
    width: 44,
    height: 44,
  },
  title: {
    color: uploadDropzoneColors.navy,
    fontSize: 16,
    lineHeight: 21,
    fontWeight: '800',
    fontFamily: fonts.regular,
    textAlign: 'center',
  },
  body: {
    color: uploadDropzoneColors.textMuted,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '500',
    fontFamily: fonts.regular,
    textAlign: 'center',
  },
  selectedList: {
    width: '100%',
    gap: 8,
  },
  selectedFileCard: {
    width: '100%',
    borderRadius: 16,
    borderWidth: 1,
    borderColor: uploadDropzoneColors.borderSoft,
    backgroundColor: uploadDropzoneColors.surface,
    paddingVertical: 12,
    paddingHorizontal: 16,
    gap: 8,
    flexDirection: 'row',
    alignItems: 'center',
  },
  selectedFileCopy: {
    flex: 1,
    gap: 4,
  },
  selectedFileName: {
    color: uploadDropzoneColors.navy,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '800',
    fontFamily: fonts.regular,
  },
  selectedFileMeta: {
    color: uploadDropzoneColors.textMuted,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '500',
    fontFamily: fonts.regular,
  },
  removeButton: {
    width: 28,
    height: 28,
    borderRadius: 999,
    backgroundColor: uploadDropzoneColors.surfaceSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  fileActionButton: {
    width: 32,
    height: 32,
    borderRadius: 999,
    backgroundColor: uploadDropzoneColors.surfaceSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  removeButtonLabel: {
    color: uploadDropzoneColors.primary,
    fontSize: 12,
    lineHeight: 12,
    fontWeight: '800',
    fontFamily: fonts.regular,
  },
  metaRow: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  metaChip: {
    borderRadius: 999,
    backgroundColor: uploadDropzoneColors.surfaceSoft,
    paddingVertical: 7,
    paddingHorizontal: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  metaChipLabel: {
    color: uploadDropzoneColors.primary,
    fontSize: 10,
    lineHeight: 12,
    fontWeight: '700',
    fontFamily: fonts.regular,
    letterSpacing: 0.4,
  },
});
